CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar NOT NULL UNIQUE,
  password_hash varchar NOT NULL
);

CREATE TABLE roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL UNIQUE
);

CREATE TABLE user_roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id int NOT NULL,
  roles_id int NOT NULL
);

CREATE TABLE request_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id int,
  ip_address inet NOT NULL,
  method varchar NOT NULL CHECK (method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')),
  endpoint varchar NOT NULL,
  query_params varchar,
  request_payload text,
  status_code integer NOT NULL,
  response_time_ms integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address inet NOT NULL,
  alert_type varchar NOT NULL CHECK (alert_type IN ('bruteforce', 'idor', 'scraping', 'rate_limit', 'sql_injection', 'endpoint_fuzzing')),
  anomaly_score float NOT NULL,
  pattern_started_at timestamptz NOT NULL,
  pattern_ended_at timestamptz NOT NULL,
  status varchar NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewed', 'false_positive', 'confirmed')),
  reviewed_by int,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alert_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_logs_id int UNIQUE NOT NULL,
  alerts_id int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE user_roles ADD FOREIGN KEY (users_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE user_roles ADD FOREIGN KEY (roles_id) REFERENCES roles (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE request_logs ADD FOREIGN KEY (users_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE alerts ADD FOREIGN KEY (reviewed_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE alert_logs ADD FOREIGN KEY (request_logs_id) REFERENCES request_logs (id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE alert_logs ADD FOREIGN KEY (alerts_id) REFERENCES alerts (id) DEFERRABLE INITIALLY IMMEDIATE;

-- Índices para las queries de detección
CREATE INDEX idx_request_logs_ip ON request_logs (ip_address);
CREATE INDEX idx_request_logs_created_at ON request_logs (created_at);
CREATE INDEX idx_request_logs_users_id ON request_logs (users_id);
CREATE INDEX idx_alerts_status ON alerts (status);